name: Deploy nginx

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v2

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      - name: Configure Docker for gcloud
        run: |
          echo Y | gcloud auth configure-docker asia-southeast2-docker.pkg.dev

      - name: Build and Push Docker Image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          docker buildx build -t asia-southeast2-docker.pkg.dev/$GOOGLE_PROJECT/demo/nginx:latest .
          docker push asia-southeast2-docker.pkg.dev/$GOOGLE_PROJECT/demo/nginx:latest
